### PR TITLE
Start a machine on Digital Ocean

### PR DESCRIPTION
**Pull request by jacobkiers**
Hi, when testing this, I had trouble getting it to start a machine on Digital Ocean.

It took a bit of debugging, but in the end I got it to start a machine.

### CODE REVIEW

**Comment by jacobkiers** [comment]
I'm not really familiar with go, so I hope this code is up to spec.

_After_ the machine is started, I still get an error during setup. Something with an external project called Lite Engine, apparently. This seems to me to be a different bug than the one I'm addressing in this PR.

```
TRAC[0401] RetryHealth: health check completed           duration=1m33.229937306s
TRAC[0401] LE.RetryHealth check complete                 func=engine.Setup id=331071750 ip=206.189.55.168 pool=drone-ci-pool response="&{Version:0.4.6 OK:true}"
TRAC[0401] Calling LE.Setup                              func=engine.Setup id=331071750 ip=206.189.55.168 pool=drone-ci-pool request="&{Envs:map[] Network:{ID:drone-pISqm1MHMsv8K7WwrOkw Labels:map[io.drone:true io.drone.build.number:17 io.drone.created:1670951269 io.drone.expires:1670958469 io.drone.protected:false io.drone.repo.name:drone-test io.drone.repo.namespace:jjkiers io.drone.repo.slug:jjkiers/drone-test io.drone.stage.name:default io.drone.stage.number:1 io.drone.system.host:drone-ci.kiers.eu io.drone.system.proto:https io.drone.system.version:2.15.0 io.drone.ttl:1h0m0s] Options:map[]} Volumes:[0xc0002657f0] Secrets:[] LogConfig:{AccountID: IndirectUpload:false URL: Token:} TIConfig:{URL: Token: AccountID: OrgID: ProjectID: PipelineID: StageID: BuildID: Repo: Sha: SourceBranch: TargetBranch: CommitBranch: CommitLink:} Files:[0xc000653d70 0xc000653da0 0xc000653dd0 0xc000653e00 0xc000653e30] MountDockerSocket:<nil>}"
ERRO[0401] failed to call LE.Setup                       error="500:failed to create directory for host volume path: : mkdir : no such file or directory" func=engine.Setup id=331071750 ip=206.189.55.168 pool=drone-ci-pool
DEBU[0401] destroying the pipeline environment           build.id=24 build.number=17 repo.id=23 repo.name=drone-test repo.namespace=jjkiers stage.id=23 stage.name=default stage.number=1 thread=2
INFO[0406] destroying instance 331071750                 func=engine.Destroy id=331071750 ip=206.189.55.168 pool=drone-ci-pool
```

The full output (including some debug output that I have not pushed the code for), can be found in the attachment.

[build-failed.txt](https://github.com/drone-runners/drone-runner-aws/files/10220489/build-failed.txt)

**Comment by tphoney** [comment]
hey @jacobkiers ! thanks for the PR  👍 🔥 
i am having a look now 👁️

**Comment by tphoney** [comment]
Hey @jacobkiers i got #231 merged, which has additional fixes in. Thanks for the effort and expertise you put in !!

**Comment by jacobkiers** [comment]
@tphoney, Thanks!

**Pull request closed without merging**
